const baseStyles: Record<string, string> = {
  actionBadge: 'ml-auto rounded-full px-2.5 py-1 text-xs font-extrabold',
  actions: 'mt-6 flex flex-col gap-3 sm:flex-row',
  addButton: 'mt-2',
  allocationPanel: 'rounded-2xl bg-white/95 p-4 shadow-sm ring-1 ring-black/5',
  allocationPanelHeader: 'mb-3 flex items-center justify-between gap-3',
  allocationPanelMeta: 'text-xs font-semibold text-slate-400',
  allocationPanelTitle: 'text-sm font-extrabold text-slate-900',
  amber: 'border-amber-200 bg-amber-50',
  amountBox: 'mt-4 grid gap-2 rounded-xl bg-slate-50 p-3',
  amountBuy: 'text-emerald-700',
  amountItem: 'flex items-center justify-between gap-3',
  amountLabel: 'text-xs font-semibold text-slate-500',
  amountSell: 'text-rose-700',
  amountValue: 'text-sm font-extrabold',
  amountValueNeutral: 'text-sm font-bold text-slate-600',
  arrow: 'inline-flex transition-transform',
  arrowDown: 'inline-flex transition-transform',
  arrowOpen: 'rotate-180',
  arrowUp: 'inline-flex rotate-180 transition-transform',
  avatar: 'grid size-10 shrink-0 place-items-center rounded-full text-sm font-extrabold text-white',
  avatarBuy: 'bg-emerald-600',
  avatarSell: 'bg-rose-600',
  backButton: 'grid size-9 place-items-center rounded-full border border-slate-200 bg-white text-lg font-bold text-slate-700',
  badge: 'inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-extrabold',
  badgeHigh: 'bg-rose-100 text-rose-700',
  badgeMedium: 'bg-amber-100 text-amber-700',
  badge_loading: 'bg-slate-100 text-slate-500',
  badge_negative: 'bg-rose-100 text-rose-700',
  badge_neutral: 'bg-slate-100 text-slate-600',
  badge_positive: 'bg-emerald-100 text-emerald-700',
  badge_unavailable: 'bg-slate-100 text-slate-400',
  badgeRow: 'mt-2 flex flex-wrap items-center gap-2',
  banner: 'rounded-2xl border border-slate-200 bg-white p-4 shadow-sm',
  bigLabel: 'mt-3 flex items-center gap-2 text-3xl font-black text-white',
  bigNum: 'text-6xl font-black leading-none text-white',
  body: 'flex flex-1 flex-col gap-5 px-5 pb-28',
  brand: 'text-lg font-black text-[var(--navy)]',
  bucketLabel: 'text-sm font-bold text-slate-700',
  buy: 'bg-emerald-100 text-emerald-700',
  caption: 'mt-1 text-sm text-slate-500',
  card: 'rounded-2xl border border-slate-200 bg-white p-4 shadow-sm',
  cardAlloc: 'mt-3 block text-xs font-semibold text-slate-500',
  cardDesc: 'mt-1 block text-sm text-slate-500',
  cardEmoji: 'text-2xl',
  cardLabel: 'mt-2 block text-base font-extrabold text-slate-900',
  cardList: 'grid gap-3',
  cardSelected: 'border-[var(--navy)] bg-[var(--navy-tint)] ring-2 ring-[var(--navy)]',
  cardTrack: 'flex gap-3 overflow-x-auto pb-2',
  cardWrap: '-mx-5 overflow-hidden px-5',
  cashHint: 'text-xs font-medium text-slate-500',
  cashInput: 'min-w-0 flex-1 bg-transparent text-right text-base font-extrabold outline-none',
  cashInputRow: 'mt-3 flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2',
  cashInputWrap: 'block rounded-2xl border border-slate-200 bg-white p-4 shadow-sm',
  cashLabel: 'block text-sm font-extrabold text-slate-900',
  cashSection: 'mb-4',
  cashUnit: 'text-sm font-bold text-slate-500',
  cell: 'rounded-xl bg-slate-50 p-3',
  cellInput: 'mt-1 w-full bg-transparent text-base font-extrabold text-slate-900 outline-none',
  cellLabel: 'text-xs font-semibold text-slate-500',
  cellVal: 'mt-1 text-base font-extrabold text-slate-900',
  chart: 'relative grid aspect-square w-full place-items-center rounded-full',
  chartLabel: 'text-xs font-bold text-slate-400',
  chartValue: 'text-2xl font-black text-slate-900',
  chartWrap: 'mx-auto w-44 max-w-full',
  check: 'grid size-5 place-items-center rounded-full bg-slate-200 text-xs font-black text-white',
  closeButton: 'grid size-9 place-items-center rounded-full bg-slate-100 text-slate-700',
  content: 'grid gap-4',
  contribBar: 'flex h-2 overflow-hidden rounded-full bg-slate-100',
  contribSegment: 'h-full',
  contribValue: 'text-sm font-extrabold',
  copy: 'min-w-0 flex-1',
  count: 'rounded-full bg-[var(--navy-tint)] px-2.5 py-1 text-xs font-extrabold text-[var(--navy)]',
  ctaButton: 'mt-4',
  currentAmber: 'text-amber-700',
  currentRed: 'text-rose-700',
  date: 'text-xs font-semibold text-white/70',
  deleteBtn: 'grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-sm font-black text-slate-500',
  deltaAlert: 'text-xs font-extrabold text-amber-700',
  deltaNeutral: 'text-xs font-extrabold text-slate-400',
  desc: 'mt-3 text-sm leading-6 text-white/80',
  description: 'text-sm leading-6 text-slate-500',
  disclaimer: 'rounded-xl bg-slate-100 p-4 text-xs leading-5 text-slate-500',
  done: 'bg-emerald-600',
  dot: 'inline-block size-2 rounded-full bg-current',
  dotHigh: 'bg-rose-600',
  dotItem: 'flex items-center gap-2',
  dotLabel: 'text-xs font-semibold text-slate-600',
  dotMedium: 'bg-amber-600',
  dotRow: 'flex flex-wrap gap-2',
  dropZone: 'cursor-pointer rounded-3xl border-2 border-dashed border-slate-300 bg-white p-5 text-center shadow-sm',
  dupBadge: 'inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-xs font-extrabold text-amber-700',
  empty: 'rounded-2xl bg-white p-8 text-center text-sm font-semibold text-slate-500',
  emptyState: 'rounded-2xl border border-dashed border-slate-300 bg-white/70 p-8 text-center text-sm font-semibold text-slate-500',
  entryBlock: 'grid gap-2',
  error: 'rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700',
  eyebrow: 'text-xs font-black uppercase tracking-wider text-[var(--amber)]',
  expand: 'border-t border-slate-100 p-4',
  expandLabel: 'text-xs font-semibold text-slate-500',
  expandRow: 'flex items-center justify-between py-1',
  expandVal: 'text-sm font-bold text-slate-700',
  expertArrow: 'transition-transform',
  expertArrowOpen: 'rotate-180',
  expertHint: 'text-xs font-semibold text-slate-400',
  expertSection: 'rounded-xl bg-slate-50 p-3',
  expertToggle: 'flex w-full items-center justify-between gap-3 text-left text-sm font-extrabold text-slate-800',
  expertToggleRight: 'flex items-center gap-2',
  explainBody: 'rounded-b-2xl bg-white p-4 text-sm leading-6 text-slate-600',
  explainBtn: 'flex w-full items-center justify-between rounded-2xl bg-white p-4 text-left font-extrabold text-slate-900 shadow-sm',
  explainIcon: 'transition-transform',
  explainOpen: 'rounded-b-none',
  field: 'grid gap-2',
  fill: 'h-full rounded-full',
  formCard: 'grid gap-4 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-black/5',
  formGrid: 'grid grid-cols-2 gap-3',
  formGridTriple: 'grid grid-cols-1 gap-3 sm:grid-cols-3',
  grid: 'grid grid-cols-2 gap-3',
  header: 'px-5 py-5',
  headerBody: 'mt-5 grid gap-4',
  headerCard: 'rounded-3xl bg-[var(--navy)] p-5 text-white shadow-lg',
  headerTop: 'mb-3 flex items-center justify-between gap-3',
  headerTopRow: 'flex items-center justify-between gap-3',
  healthChip: 'rounded-2xl bg-slate-50 p-4',
  healthEyebrow: 'block text-xs font-bold text-slate-400',
  healthLabel: 'mt-1 block text-sm font-extrabold text-slate-900',
  healthScore: 'inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-sm font-bold text-white',
  healthScoreDot: 'size-2 rounded-full bg-emerald-400',
  healthScoreLabel: 'text-xs font-semibold',
  healthScoreValue: 'text-sm font-black',
  healthyTitle: 'text-3xl font-black leading-tight text-white',
  headline: 'text-3xl font-black leading-tight text-slate-950',
  helperText: 'text-xs leading-5 text-slate-500',
  hero: 'grid gap-2',
  heroCard: 'rounded-3xl bg-white p-5 shadow-sm ring-1 ring-black/5',
  hint: 'text-sm leading-6 text-slate-500',
  icon: 'grid size-5 place-items-center',
  icon_negative: 'text-rose-600',
  icon_neutral: 'text-slate-600',
  icon_positive: 'text-emerald-600',
  icon_unavailable: 'text-slate-400',
  iconWrap: 'grid size-11 shrink-0 place-items-center rounded-2xl bg-slate-100 text-white',
  iconWrap_negative: 'bg-rose-50',
  iconWrap_neutral: 'bg-slate-100',
  iconWrap_positive: 'bg-emerald-50',
  iconWrap_unavailable: 'bg-slate-50',
  implication: 'mt-3 rounded-xl bg-[var(--amber-bg)] p-3',
  implicationLabel: 'text-sm font-extrabold text-amber-800',
  implicationText: 'mt-1 text-sm leading-5 text-amber-700',
  improvementBtn: 'flex w-full items-center justify-between rounded-2xl bg-[var(--navy)] p-4 text-left text-white shadow-sm',
  improvementBtnArrow: 'text-xl font-black',
  improvementBtnMeta: 'text-xs font-semibold text-white/70',
  improvementBtnText: 'grid gap-1',
  improvementBtnTitle: 'text-base font-extrabold',
  improvementSection: 'grid gap-3',
  info: 'min-w-0 flex-1',
  inlineRetry: 'rounded-full bg-[var(--navy)] px-3 py-1.5 text-xs font-extrabold text-white',
  input: 'w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-semibold outline-none focus:ring-2 focus:ring-[var(--navy)]',
  item: 'rounded-2xl border border-slate-200 bg-white p-4 shadow-sm',
  itemActive: 'bg-[var(--navy)] text-white',
  kpiEyebrow: 'text-xs font-black uppercase tracking-wider text-[var(--amber)]',
  kpiLabel: 'text-sm font-extrabold text-slate-700',
  kpiRow: 'flex items-end gap-2',
  kpiScore: 'flex items-end gap-1',
  kpiScoreNum: 'text-5xl font-black text-slate-950',
  kpiScoreUnit: 'pb-1 text-sm font-bold text-slate-400',
  kpiSummary: 'text-sm leading-6 text-slate-600',
  label: 'text-sm font-bold text-slate-700',
  labelBadge: 'rounded-full bg-slate-100 px-2.5 py-1 text-xs font-extrabold text-slate-600',
  legend: 'grid gap-2',
  legendDot: 'size-2.5 rounded-full',
  legendItem: 'flex items-center gap-2',
  legendLabel: 'min-w-0 flex-1 text-sm font-bold text-slate-700',
  legendMeta: 'flex items-center gap-2 text-xs',
  legendShare: 'font-extrabold text-slate-900',
  legendValue: 'font-semibold text-slate-400',
  link: 'mt-4 inline-flex rounded-full bg-[var(--navy)] px-4 py-2 text-sm font-extrabold text-white',
  loadingBody: 'flex flex-1 flex-col justify-center px-5 pb-20',
  loadingSub: 'mt-3 text-sm text-slate-500',
  loadingTitle: 'mt-2 text-4xl font-black leading-tight text-slate-950',
  main: 'grid gap-4',
  manual: 'text-center text-sm font-semibold text-[var(--navy)]',
  mbtiCard: 'rounded-3xl p-5 shadow-sm',
  mbtiCode: 'text-2xl font-black',
  mbtiDesc: 'mt-3 text-sm leading-6',
  mbtiEmojiBox: 'grid size-12 place-items-center rounded-2xl bg-white/50 text-2xl',
  mbtiEyebrow: 'text-xs font-black uppercase tracking-wider opacity-70',
  mbtiGroup_analyst: 'bg-indigo-50 text-indigo-950',
  mbtiGroup_diplomat: 'bg-emerald-50 text-emerald-950',
  mbtiGroup_explorer: 'bg-amber-50 text-amber-950',
  mbtiGroup_sentinel: 'bg-sky-50 text-sky-950',
  mbtiName: 'text-sm font-bold opacity-80',
  mbtiTagline: 'mt-3 text-base font-extrabold',
  mbtiTop: 'mt-3 flex items-center gap-3',
  meta: 'flex flex-wrap gap-2',
  metaBadge: 'rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600',
  metaHint: 'text-xs font-semibold text-slate-500',
  metaRow: 'flex flex-wrap items-center gap-2',
  metric: 'grid gap-1',
  metricBox: 'rounded-xl bg-white p-3 ring-1 ring-slate-200',
  metricContrib: 'text-right text-sm font-extrabold',
  metricDesc: 'mt-2 text-xs leading-5 text-slate-500',
  metricDivider: 'h-10 w-px bg-slate-200',
  metricLabel: 'text-xs font-semibold text-slate-500',
  metricLeft: 'min-w-0',
  metricMain: 'grid grid-cols-[1fr_auto_auto] items-center gap-2',
  metricRow: 'border-t border-slate-200 py-3 first:border-t-0',
  metricSource: 'mt-1 text-xs leading-5 text-slate-500',
  metricStatus: 'text-xs font-extrabold',
  metricTitle: 'text-sm font-extrabold text-slate-900',
  metricValue: 'text-lg font-black text-slate-900',
  metrics: 'mt-4 flex items-center gap-5',
  moneyField: 'flex items-center rounded-xl border border-slate-200 bg-white px-3',
  moneyUnit: 'text-xs font-bold text-slate-400',
  name: 'font-extrabold text-slate-900',
  nameRow: 'flex flex-wrap items-center gap-2',
  nameWrap: 'flex min-w-0 flex-wrap items-center gap-2',
  nav: 'sticky bottom-3 z-20 mx-4 flex items-center justify-around rounded-2xl bg-white/95 p-2 shadow-lg ring-1 ring-black/10 backdrop-blur',
  note: 'rounded-xl bg-slate-50 p-3',
  noteText: 'text-sm leading-6 text-slate-600',
  overlay: 'fixed inset-0 z-50 flex items-end justify-center bg-black/40 px-3',
  page: 'grid gap-5 px-5 pb-24',
  pct: 'text-sm font-black text-slate-900',
  percent: 'text-sm font-extrabold text-slate-900',
  priceRange: 'rounded-xl bg-slate-50 p-3',
  priceRangeFill: 'h-full rounded-full bg-[var(--navy)]',
  priceRangeHeader: 'flex items-center justify-between',
  priceRangeLabel: 'text-xs font-bold text-slate-500',
  priceRangeScale: 'mt-2 flex justify-between text-xs text-slate-400',
  priceRangeThumb: 'absolute top-1/2 size-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[var(--navy)] ring-2 ring-white',
  priceRangeTrack: 'relative mt-2 h-2 rounded-full bg-slate-200',
  priceRangeValue: 'text-xs font-extrabold text-slate-900',
  primaryButton: 'rounded-xl bg-[var(--navy)] px-4 py-3 text-sm font-extrabold text-white',
  privacy: 'text-center text-xs leading-5 text-slate-500',
  problemList: 'grid gap-3',
  progFill: 'h-full rounded-full bg-[var(--navy)] transition-all',
  progLabel: 'mt-2 text-xs font-semibold text-slate-500',
  progTrack: 'h-2 overflow-hidden rounded-full bg-slate-200',
  progWrap: 'mt-6',
  quizChoice: 'rounded-xl border border-slate-200 bg-white px-3 py-3 text-left text-sm font-bold text-slate-700',
  quizChoiceSelected: 'border-[var(--navy)] bg-[var(--navy-tint)] text-[var(--navy)]',
  quizChoices: 'grid gap-2',
  quizEntry: 'flex items-center justify-between gap-3 rounded-2xl bg-white p-4 shadow-sm',
  quizEntryButton: 'shrink-0 rounded-xl bg-[var(--navy)] px-3 py-2 text-sm font-extrabold text-white',
  quizEntryDesc: 'mt-1 text-xs leading-5 text-slate-500',
  quizEntryTitle: 'text-sm font-extrabold text-slate-900',
  quizNav: 'mt-4 flex justify-between gap-2',
  quizNavButton: 'rounded-xl border border-slate-200 px-4 py-2 text-sm font-extrabold text-slate-600',
  quizNavButtonPrimary: 'rounded-xl bg-[var(--navy)] px-4 py-2 text-sm font-extrabold text-white disabled:opacity-40',
  quizProgress: 'mb-3 flex items-center justify-between',
  quizProgressLabel: 'text-xs font-black uppercase tracking-wider text-[var(--amber)]',
  quizProgressStep: 'text-xs font-bold text-slate-400',
  quizQuestion: 'mb-3 text-lg font-black text-slate-900',
  quizResult: 'rounded-xl bg-emerald-50 p-3 text-sm font-extrabold text-emerald-700',
  quizWrap: 'rounded-2xl bg-white p-4 shadow-sm',
  red: 'border-rose-200 bg-rose-50',
  referenceBody: 'min-w-0 flex-1',
  referenceDot: 'mt-2 size-1.5 rounded-full bg-slate-300',
  referenceItem: 'flex gap-2',
  referenceName: 'text-sm font-bold text-slate-700',
  referenceNote: 'text-xs leading-5 text-slate-500',
  referenceSection: 'grid gap-2 rounded-xl bg-slate-50 p-3',
  referenceTitle: 'text-sm font-extrabold text-slate-900',
  referenceValue: 'ml-2 text-xs font-bold text-slate-500',
  refreshButton: 'rounded-full bg-[var(--navy)] px-3 py-1.5 text-xs font-extrabold text-white',
  retryBtn: 'rounded-full bg-white/15 px-3 py-1.5 text-xs font-extrabold text-white',
  right: 'ml-auto flex items-center gap-2',
  row: 'grid gap-2',
  row1: 'flex items-start justify-between gap-3',
  rowHeader: 'flex items-center justify-between gap-3',
  rowList: 'grid gap-3',
  rowMeta: 'flex items-center gap-2',
  rowTop: 'flex items-center justify-between gap-3',
  scoreArrow: 'text-xl font-black text-slate-400',
  scoreBlock: 'grid gap-1 text-center',
  scoreCard: 'grid grid-cols-[1fr_auto_1fr] items-center gap-3 rounded-2xl bg-slate-50 p-4',
  scoreLabel: 'text-xs font-bold text-slate-500',
  scoreRing: 'grid shrink-0 place-items-center rounded-full border-4 border-current',
  scoreRingLabel: 'text-sm font-black',
  scoreValue: 'text-2xl font-black text-slate-900',
  scoreValueIdeal: 'text-emerald-700',
  scroll: 'pb-[calc(96px+env(safe-area-inset-bottom))]',
  secondary: 'text-slate-500',
  secondaryButton: 'rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-extrabold text-slate-700',
  section: 'grid gap-3',
  sectionEyebrow: 'text-xs font-black uppercase tracking-wider text-[var(--amber)]',
  sectionHeader: 'flex items-center justify-between gap-3',
  sectionLabel: 'text-sm font-black text-slate-500',
  sectionMeta: 'rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-500',
  sectionTitle: 'text-lg font-black text-slate-900',
  sector: 'rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-500',
  sectorSelect: 'flex-1',
  sectorSelectSm: 'min-w-32',
  select: 'rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-700',
  selectSm: 'rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs font-bold text-slate-700',
  selectionRequired: 'rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-700',
  sell: 'bg-rose-100 text-rose-700',
  shareBtn: 'mt-4 w-full rounded-xl bg-white/70 px-4 py-3 text-sm font-extrabold',
  sheet: 'max-h-[88dvh] w-full max-w-mobile overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl',
  signalBtn: 'flex w-full items-center justify-between rounded-2xl bg-white p-4 text-left shadow-sm',
  signalBtnArrow: 'text-xl font-black text-[var(--navy)]',
  signalBtnMeta: 'text-xs font-semibold text-slate-500',
  signalBtnText: 'grid gap-1',
  signalBtnTitle: 'text-base font-extrabold text-slate-900',
  skeletonBadge: 'h-6 w-14 animate-pulse rounded-full bg-slate-200',
  skeletonCard: 'rounded-2xl bg-white p-4 shadow-sm',
  skeletonHealthChip: 'h-20 animate-pulse rounded-2xl bg-slate-100',
  skeletonIcon: 'size-11 animate-pulse rounded-2xl bg-slate-200',
  skeletonKpiEyebrow: 'h-3 w-24 animate-pulse rounded bg-slate-200',
  skeletonKpiLabel: 'h-5 w-20 animate-pulse rounded bg-slate-200',
  skeletonKpiRow: 'mt-4 flex items-end gap-3',
  skeletonKpiScore: 'h-12 w-24 animate-pulse rounded bg-slate-200',
  skeletonLine: 'mt-3 h-3 w-full animate-pulse rounded bg-slate-200',
  skeletonRow: 'flex items-center gap-3',
  skeletonText: 'min-w-0 flex-1',
  skeletonTitleShort: 'h-4 w-32 animate-pulse rounded bg-slate-200',
  slider: 'w-full accent-[var(--navy)]',
  sliderLabel: 'text-sm font-bold text-slate-700',
  sliderList: 'grid gap-4',
  sliderMeta: 'mb-2 flex items-center justify-between',
  sliderRow: 'block',
  sliderValue: 'text-sm font-black text-slate-900',
  source: 'text-center text-xs text-slate-400',
  spinning: 'animate-spin border-2 border-slate-300 border-t-[var(--navy)] bg-transparent',
  stateCard: 'rounded-2xl bg-white p-5 text-center text-sm font-semibold text-slate-500 shadow-sm',
  stepList: 'mt-8 grid gap-3',
  stepName: 'text-sm font-bold text-slate-700',
  stepRow: 'flex items-center gap-3 opacity-0 transition-opacity',
  stepVisible: 'opacity-100',
  stockInfo: 'min-w-0',
  stockRow: 'flex items-center gap-3',
  sub: 'mt-4 text-lg font-semibold leading-7 text-slate-600',
  subline: 'mt-2 text-sm text-white/70',
  summary: 'mt-2 text-sm leading-6 text-slate-600',
  summaryCard: 'rounded-2xl bg-white p-4 shadow-sm',
  summaryClamp: 'mt-2 line-clamp-2 text-sm leading-6 text-slate-500',
  summaryHeader: 'flex items-start justify-between gap-3',
  summaryLegend: 'mt-3 text-xs leading-5 text-slate-500',
  summaryTile: 'rounded-xl p-3 text-center',
  summaryTileLabel: 'mt-1 text-xs font-bold',
  summaryTileValue: 'text-2xl font-black',
  summaryTiles: 'mt-4 grid grid-cols-3 gap-2',
  summaryTitle: 'text-base font-black text-slate-900',
  table: 'w-full border-separate border-spacing-0',
  tableHeader: 'grid grid-cols-[1fr_auto_auto] gap-2 text-xs font-black text-slate-400',
  tableWrap: 'overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-slate-200',
  targetCheck: 'text-emerald-600',
  targetError: 'mt-3 rounded-xl bg-rose-50 p-3 text-sm font-bold text-rose-700',
  targetHeader: 'flex items-start justify-between gap-3',
  targetHint: 'text-sm text-slate-500',
  targetLabel: 'text-xs font-bold text-slate-400',
  targetLine: 'absolute top-0 h-full w-0.5 bg-slate-900',
  targetOver: 'text-amber-700',
  targetSection: 'rounded-2xl bg-white p-4 shadow-sm',
  targetSummary: 'mt-4 flex items-center gap-2 rounded-xl p-3',
  targetSummaryInvalid: 'bg-amber-50 text-amber-800',
  targetSummaryLabel: 'text-sm font-bold',
  targetSummaryMessage: 'ml-auto text-xs font-semibold',
  targetSummaryValid: 'bg-emerald-50 text-emerald-800',
  targetSummaryValue: 'text-lg font-black',
  targetTitle: 'text-lg font-black text-slate-900',
  td: 'border-b border-slate-100 p-2 align-middle',
  tdAction: 'border-b border-slate-100 p-2 text-right',
  tdInput: 'w-24 rounded-lg border border-slate-200 px-2 py-1.5 text-right text-xs font-bold outline-none',
  tdName: 'border-b border-slate-100 p-2 align-middle',
  tdNum: 'border-b border-slate-100 p-2 text-right align-middle',
  tdPct: 'font-black text-slate-900',
  th: 'bg-slate-50 p-2 text-left text-xs font-black text-slate-500',
  thContrib: 'text-right',
  thLabel: 'text-left',
  thNum: 'text-right',
  thStatus: 'text-center',
  thead: 'text-xs',
  ticker: 'text-xs font-bold text-slate-400',
  title: 'text-xl font-black text-slate-950',
  titleRow: 'flex items-center justify-between gap-3',
  toggle: 'flex w-full items-center justify-between gap-3 text-left',
  top: 'grid gap-3',
  topSector: 'rounded-full bg-slate-100 px-3 py-1 text-xs font-extrabold text-slate-600',
  track: 'relative h-2 overflow-hidden rounded-full bg-slate-200',
  trackFill: 'h-full rounded-full bg-[var(--navy)]',
  trackFillTarget: 'bg-emerald-600',
  tr: 'bg-white',
  trDup: 'bg-amber-50',
  wrap: 'flex min-h-dvh flex-col bg-[var(--bg)]',
  whyArrow: 'transition-transform',
  whyArrowOpen: 'rotate-180',
  whySection: 'mt-3 border-t border-slate-100 pt-3',
  whyText: 'mt-2 text-sm leading-6 text-slate-600',
  whyToggle: 'flex w-full items-center justify-between text-sm font-bold text-slate-600',
  zoneDesc: 'mt-2 text-sm leading-6 text-slate-500',
  zoneTitle: 'mt-3 text-lg font-black text-slate-900',
}

export const tailwindStyles = new Proxy(baseStyles, {
  get(target, prop: string | symbol) {
    if (typeof prop !== 'string') {
      return ''
    }

    return target[prop] ?? ''
  },
}) as Record<string, string>
